# config/zedm_yaml
# Parameters for Stereolabs ZED mini camera
---
/**:
    ros__parameters:
        general:
            camera_model: 'zedm'
            camera_name: 'zedm' # overwritten by launch file
            grab_resolution: 'VGA' # The native camera grab resolution. 'HD2K', 'HD1080', 'HD720', 'VGA', 'AUTO'
            grab_frame_rate: 15 # ZED SDK internal grabbing rate
            pub_resolution: 'NATIVE' # The resolution used for image and depth map publishing. 'NATIVE' to use the same `general.grab_resolution` - `CUSTOM` to apply the `general.pub_downscale_factor` downscale factory to reduce bandwidth in transmission
            pub_downscale_factor: 1.0

        video:
            brightness: 4 # [DYNAMIC] Image brightness. Range: 0-8
            contrast: 4 # [DYNAMIC] Image contrast. Range: 0-8
            hue: 0 # [DYNAMIC] Image hue. Range: 0 to 11
            publish_left_right: true # Publish both left and right images

        depth:
            depth_mode: "ULTRA" # Depth computation mode. Options: 'PERFORMANCE', 'QUALITY', 'ULTRA'
            min_depth: 0.01 # Min: 0.01, Max: 3.0
            max_depth: 10.0 # Min: 0.5, Max: 15.0
        