camera_names:
  - zed_front
  - zed_left
  - zed_right

show_images:
  - false # True to show debug cv2 windows with camera images

human_record:
  - false # True to record human demos, false to record robot demos through teleop

eef_frame_name:
  - tcp_link

ur_topics_to_record:
  - /joint_states

teleop_state_topic: /teleop_state

set_robot_to_home_service: /set_robot_to_home

task_name: pick_and_place
variation_id: 0
traj_count_id: 0

saving_directory: /home/user/saved_trajectories