planning_components: 
  - arm_tcp

home_joint_names: 
 - ['elbow_joint', 'shoulder_lift_joint', 'shoulder_pan_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']

home_joint_positions:
  - [2.35, -2.35, -1.57, -1.57, -1.57, 0]

controller_to_run:
  - scaled_joint_trajectory_controller

controller_to_stop:
  - forward_position_controller